/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: ipc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "ipc.pb-c.h"
void   ipc__ipcname__init
                     (Ipc__IPCName         *message)
{
  static Ipc__IPCName init_value = IPC__IPCNAME__INIT;
  *message = init_value;
}
size_t ipc__ipcname__get_packed_size
                     (const Ipc__IPCName *message)
{
  assert(message->base.descriptor == &ipc__ipcname__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__ipcname__pack
                     (const Ipc__IPCName *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__ipcname__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__ipcname__pack_to_buffer
                     (const Ipc__IPCName *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__ipcname__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__IPCName *
       ipc__ipcname__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__IPCName *)
     protobuf_c_message_unpack (&ipc__ipcname__descriptor,
                                allocator, len, data);
}
void   ipc__ipcname__free_unpacked
                     (Ipc__IPCName *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__ipcname__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__add_ipcobject__init
                     (Ipc__AddIPCObject         *message)
{
  static Ipc__AddIPCObject init_value = IPC__ADD_IPCOBJECT__INIT;
  *message = init_value;
}
size_t ipc__add_ipcobject__get_packed_size
                     (const Ipc__AddIPCObject *message)
{
  assert(message->base.descriptor == &ipc__add_ipcobject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__add_ipcobject__pack
                     (const Ipc__AddIPCObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__add_ipcobject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__add_ipcobject__pack_to_buffer
                     (const Ipc__AddIPCObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__add_ipcobject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__AddIPCObject *
       ipc__add_ipcobject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__AddIPCObject *)
     protobuf_c_message_unpack (&ipc__add_ipcobject__descriptor,
                                allocator, len, data);
}
void   ipc__add_ipcobject__free_unpacked
                     (Ipc__AddIPCObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__add_ipcobject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__update_ipcobject__init
                     (Ipc__UpdateIPCObject         *message)
{
  static Ipc__UpdateIPCObject init_value = IPC__UPDATE_IPCOBJECT__INIT;
  *message = init_value;
}
size_t ipc__update_ipcobject__get_packed_size
                     (const Ipc__UpdateIPCObject *message)
{
  assert(message->base.descriptor == &ipc__update_ipcobject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__update_ipcobject__pack
                     (const Ipc__UpdateIPCObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__update_ipcobject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__update_ipcobject__pack_to_buffer
                     (const Ipc__UpdateIPCObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__update_ipcobject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__UpdateIPCObject *
       ipc__update_ipcobject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__UpdateIPCObject *)
     protobuf_c_message_unpack (&ipc__update_ipcobject__descriptor,
                                allocator, len, data);
}
void   ipc__update_ipcobject__free_unpacked
                     (Ipc__UpdateIPCObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__update_ipcobject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__change_ipcname__init
                     (Ipc__ChangeIPCName         *message)
{
  static Ipc__ChangeIPCName init_value = IPC__CHANGE_IPCNAME__INIT;
  *message = init_value;
}
size_t ipc__change_ipcname__get_packed_size
                     (const Ipc__ChangeIPCName *message)
{
  assert(message->base.descriptor == &ipc__change_ipcname__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__change_ipcname__pack
                     (const Ipc__ChangeIPCName *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__change_ipcname__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__change_ipcname__pack_to_buffer
                     (const Ipc__ChangeIPCName *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__change_ipcname__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__ChangeIPCName *
       ipc__change_ipcname__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__ChangeIPCName *)
     protobuf_c_message_unpack (&ipc__change_ipcname__descriptor,
                                allocator, len, data);
}
void   ipc__change_ipcname__free_unpacked
                     (Ipc__ChangeIPCName *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__change_ipcname__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__ipcobject_list__init
                     (Ipc__IPCObjectList         *message)
{
  static Ipc__IPCObjectList init_value = IPC__IPCOBJECT_LIST__INIT;
  *message = init_value;
}
size_t ipc__ipcobject_list__get_packed_size
                     (const Ipc__IPCObjectList *message)
{
  assert(message->base.descriptor == &ipc__ipcobject_list__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__ipcobject_list__pack
                     (const Ipc__IPCObjectList *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__ipcobject_list__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__ipcobject_list__pack_to_buffer
                     (const Ipc__IPCObjectList *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__ipcobject_list__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__IPCObjectList *
       ipc__ipcobject_list__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__IPCObjectList *)
     protobuf_c_message_unpack (&ipc__ipcobject_list__descriptor,
                                allocator, len, data);
}
void   ipc__ipcobject_list__free_unpacked
                     (Ipc__IPCObjectList *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__ipcobject_list__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__module_name__init
                     (Ipc__ModuleName         *message)
{
  static Ipc__ModuleName init_value = IPC__MODULE_NAME__INIT;
  *message = init_value;
}
size_t ipc__module_name__get_packed_size
                     (const Ipc__ModuleName *message)
{
  assert(message->base.descriptor == &ipc__module_name__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__module_name__pack
                     (const Ipc__ModuleName *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__module_name__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__module_name__pack_to_buffer
                     (const Ipc__ModuleName *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__module_name__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__ModuleName *
       ipc__module_name__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__ModuleName *)
     protobuf_c_message_unpack (&ipc__module_name__descriptor,
                                allocator, len, data);
}
void   ipc__module_name__free_unpacked
                     (Ipc__ModuleName *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__module_name__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__module_state__init
                     (Ipc__ModuleState         *message)
{
  static Ipc__ModuleState init_value = IPC__MODULE_STATE__INIT;
  *message = init_value;
}
size_t ipc__module_state__get_packed_size
                     (const Ipc__ModuleState *message)
{
  assert(message->base.descriptor == &ipc__module_state__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__module_state__pack
                     (const Ipc__ModuleState *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__module_state__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__module_state__pack_to_buffer
                     (const Ipc__ModuleState *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__module_state__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__ModuleState *
       ipc__module_state__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__ModuleState *)
     protobuf_c_message_unpack (&ipc__module_state__descriptor,
                                allocator, len, data);
}
void   ipc__module_state__free_unpacked
                     (Ipc__ModuleState *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__module_state__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__remove_ipcobject__init
                     (Ipc__RemoveIPCObject         *message)
{
  static Ipc__RemoveIPCObject init_value = IPC__REMOVE_IPCOBJECT__INIT;
  *message = init_value;
}
size_t ipc__remove_ipcobject__get_packed_size
                     (const Ipc__RemoveIPCObject *message)
{
  assert(message->base.descriptor == &ipc__remove_ipcobject__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__remove_ipcobject__pack
                     (const Ipc__RemoveIPCObject *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__remove_ipcobject__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__remove_ipcobject__pack_to_buffer
                     (const Ipc__RemoveIPCObject *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__remove_ipcobject__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__RemoveIPCObject *
       ipc__remove_ipcobject__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__RemoveIPCObject *)
     protobuf_c_message_unpack (&ipc__remove_ipcobject__descriptor,
                                allocator, len, data);
}
void   ipc__remove_ipcobject__free_unpacked
                     (Ipc__RemoveIPCObject *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__remove_ipcobject__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__ipcmessage__init
                     (Ipc__IPCMessage         *message)
{
  static Ipc__IPCMessage init_value = IPC__IPCMESSAGE__INIT;
  *message = init_value;
}
size_t ipc__ipcmessage__get_packed_size
                     (const Ipc__IPCMessage *message)
{
  assert(message->base.descriptor == &ipc__ipcmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__ipcmessage__pack
                     (const Ipc__IPCMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__ipcmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__ipcmessage__pack_to_buffer
                     (const Ipc__IPCMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__ipcmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__IPCMessage *
       ipc__ipcmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__IPCMessage *)
     protobuf_c_message_unpack (&ipc__ipcmessage__descriptor,
                                allocator, len, data);
}
void   ipc__ipcmessage__free_unpacked
                     (Ipc__IPCMessage *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__ipcmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   ipc__ping__init
                     (Ipc__Ping         *message)
{
  static Ipc__Ping init_value = IPC__PING__INIT;
  *message = init_value;
}
size_t ipc__ping__get_packed_size
                     (const Ipc__Ping *message)
{
  assert(message->base.descriptor == &ipc__ping__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t ipc__ping__pack
                     (const Ipc__Ping *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &ipc__ping__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t ipc__ping__pack_to_buffer
                     (const Ipc__Ping *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &ipc__ping__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Ipc__Ping *
       ipc__ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Ipc__Ping *)
     protobuf_c_message_unpack (&ipc__ping__descriptor,
                                allocator, len, data);
}
void   ipc__ping__free_unpacked
                     (Ipc__Ping *message,
                      ProtobufCAllocator *allocator)
{
  assert(message->base.descriptor == &ipc__ping__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor ipc__ipcname__field_descriptors[3] =
{
  {
    "module_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__IPCName, module_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "host_name",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__IPCName, host_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conn_id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__IPCName, conn_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__ipcname__field_indices_by_name[] = {
  2,   /* field[2] = conn_id */
  1,   /* field[1] = host_name */
  0,   /* field[0] = module_name */
};
static const ProtobufCIntRange ipc__ipcname__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ipc__ipcname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.IPCName",
  "IPCName",
  "Ipc__IPCName",
  "ipc",
  sizeof(Ipc__IPCName),
  3,
  ipc__ipcname__field_descriptors,
  ipc__ipcname__field_indices_by_name,
  1,  ipc__ipcname__number_ranges,
  (ProtobufCMessageInit) ipc__ipcname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__add_ipcobject__field_descriptors[4] =
{
  {
    "ipc_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ipc__AddIPCObject, ipc_name),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__AddIPCObject, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ipc__AddIPCObject, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__AddIPCObject, access_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__add_ipcobject__field_indices_by_name[] = {
  3,   /* field[3] = access_id */
  1,   /* field[1] = ip */
  0,   /* field[0] = ipc_name */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange ipc__add_ipcobject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ipc__add_ipcobject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.AddIPCObject",
  "AddIPCObject",
  "Ipc__AddIPCObject",
  "ipc",
  sizeof(Ipc__AddIPCObject),
  4,
  ipc__add_ipcobject__field_descriptors,
  ipc__add_ipcobject__field_indices_by_name,
  1,  ipc__add_ipcobject__number_ranges,
  (ProtobufCMessageInit) ipc__add_ipcobject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__update_ipcobject__field_descriptors[2] =
{
  {
    "ipc_old_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ipc__UpdateIPCObject, ipc_old_name),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipc_new_name",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ipc__UpdateIPCObject, ipc_new_name),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__update_ipcobject__field_indices_by_name[] = {
  1,   /* field[1] = ipc_new_name */
  0,   /* field[0] = ipc_old_name */
};
static const ProtobufCIntRange ipc__update_ipcobject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ipc__update_ipcobject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.UpdateIPCObject",
  "UpdateIPCObject",
  "Ipc__UpdateIPCObject",
  "ipc",
  sizeof(Ipc__UpdateIPCObject),
  2,
  ipc__update_ipcobject__field_descriptors,
  ipc__update_ipcobject__field_indices_by_name,
  1,  ipc__update_ipcobject__number_ranges,
  (ProtobufCMessageInit) ipc__update_ipcobject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__change_ipcname__field_descriptors[1] =
{
  {
    "ipc_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ipc__ChangeIPCName, ipc_name),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__change_ipcname__field_indices_by_name[] = {
  0,   /* field[0] = ipc_name */
};
static const ProtobufCIntRange ipc__change_ipcname__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ipc__change_ipcname__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.ChangeIPCName",
  "ChangeIPCName",
  "Ipc__ChangeIPCName",
  "ipc",
  sizeof(Ipc__ChangeIPCName),
  1,
  ipc__change_ipcname__field_descriptors,
  ipc__change_ipcname__field_indices_by_name,
  1,  ipc__change_ipcname__number_ranges,
  (ProtobufCMessageInit) ipc__change_ipcname__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__ipcobject_list__field_descriptors[2] =
{
  {
    "ipc_object",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ipc__IPCObjectList, n_ipc_object),
    offsetof(Ipc__IPCObjectList, ipc_object),
    &ipc__add_ipcobject__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_id",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__IPCObjectList, access_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__ipcobject_list__field_indices_by_name[] = {
  1,   /* field[1] = access_id */
  0,   /* field[0] = ipc_object */
};
static const ProtobufCIntRange ipc__ipcobject_list__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor ipc__ipcobject_list__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.IPCObjectList",
  "IPCObjectList",
  "Ipc__IPCObjectList",
  "ipc",
  sizeof(Ipc__IPCObjectList),
  2,
  ipc__ipcobject_list__field_descriptors,
  ipc__ipcobject_list__field_indices_by_name,
  1,  ipc__ipcobject_list__number_ranges,
  (ProtobufCMessageInit) ipc__ipcobject_list__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__module_name__field_descriptors[6] =
{
  {
    "ipc_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleName, ipc_name),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleName, ip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "port",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleName, port),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "access_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleName, access_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_exist",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Ipc__ModuleName, has_is_exist),
    offsetof(Ipc__ModuleName, is_exist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conn_id",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleName, conn_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__module_name__field_indices_by_name[] = {
  3,   /* field[3] = access_id */
  5,   /* field[5] = conn_id */
  1,   /* field[1] = ip */
  0,   /* field[0] = ipc_name */
  4,   /* field[4] = is_exist */
  2,   /* field[2] = port */
};
static const ProtobufCIntRange ipc__module_name__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor ipc__module_name__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.ModuleName",
  "ModuleName",
  "Ipc__ModuleName",
  "ipc",
  sizeof(Ipc__ModuleName),
  6,
  ipc__module_name__field_descriptors,
  ipc__module_name__field_indices_by_name,
  1,  ipc__module_name__number_ranges,
  (ProtobufCMessageInit) ipc__module_name__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__module_state__field_descriptors[3] =
{
  {
    "exist",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleState, exist),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rndVal",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleState, rndval),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__ModuleState, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__module_state__field_indices_by_name[] = {
  0,   /* field[0] = exist */
  2,   /* field[2] = id */
  1,   /* field[1] = rndVal */
};
static const ProtobufCIntRange ipc__module_state__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor ipc__module_state__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.ModuleState",
  "ModuleState",
  "Ipc__ModuleState",
  "ipc",
  sizeof(Ipc__ModuleState),
  3,
  ipc__module_state__field_descriptors,
  ipc__module_state__field_indices_by_name,
  1,  ipc__module_state__number_ranges,
  (ProtobufCMessageInit) ipc__module_state__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__remove_ipcobject__field_descriptors[1] =
{
  {
    "ipc_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__RemoveIPCObject, ipc_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__remove_ipcobject__field_indices_by_name[] = {
  0,   /* field[0] = ipc_name */
};
static const ProtobufCIntRange ipc__remove_ipcobject__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor ipc__remove_ipcobject__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.RemoveIPCObject",
  "RemoveIPCObject",
  "Ipc__RemoveIPCObject",
  "ipc",
  sizeof(Ipc__RemoveIPCObject),
  1,
  ipc__remove_ipcobject__field_descriptors,
  ipc__remove_ipcobject__field_indices_by_name,
  1,  ipc__remove_ipcobject__number_ranges,
  (ProtobufCMessageInit) ipc__remove_ipcobject__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor ipc__ipcmessage__field_descriptors[4] =
{
  {
    "message_name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Ipc__IPCMessage, message_name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipc_path",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ipc__IPCMessage, n_ipc_path),
    offsetof(Ipc__IPCMessage, ipc_path),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ipc_sender",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Ipc__IPCMessage, n_ipc_sender),
    offsetof(Ipc__IPCMessage, ipc_sender),
    &ipc__ipcname__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Ipc__IPCMessage, has_message),
    offsetof(Ipc__IPCMessage, message),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned ipc__ipcmessage__field_indices_by_name[] = {
  1,   /* field[1] = ipc_path */
  2,   /* field[2] = ipc_sender */
  3,   /* field[3] = message */
  0,   /* field[0] = message_name */
};
static const ProtobufCIntRange ipc__ipcmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor ipc__ipcmessage__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.IPCMessage",
  "IPCMessage",
  "Ipc__IPCMessage",
  "ipc",
  sizeof(Ipc__IPCMessage),
  4,
  ipc__ipcmessage__field_descriptors,
  ipc__ipcmessage__field_indices_by_name,
  1,  ipc__ipcmessage__number_ranges,
  (ProtobufCMessageInit) ipc__ipcmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define ipc__ping__field_descriptors NULL
#define ipc__ping__field_indices_by_name NULL
#define ipc__ping__number_ranges NULL
const ProtobufCMessageDescriptor ipc__ping__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ipc.Ping",
  "Ping",
  "Ipc__Ping",
  "ipc",
  sizeof(Ipc__Ping),
  0,
  ipc__ping__field_descriptors,
  ipc__ping__field_indices_by_name,
  0,  ipc__ping__number_ranges,
  (ProtobufCMessageInit) ipc__ping__init,
  NULL,NULL,NULL    /* reserved[123] */
};
