#!/bin/sh
### BEGIN INIT INFO
# Provides:          twndeamon
# Required-Start:    $remote_fs $syslog $network-manager
# Required-Stop:     $remote_fs $syslog $network-manager
# Default-Start:     3 4 5
# Default-Stop:	     3 4 5
# Short-Description: twainet deamon
# Description:       Twainet is a simple interprocess messaging system, used
#                    for sending messages between applications.
### END INIT INFO
# -*- coding: utf-8 -*-
# Copyright © 2015 Alexey Volokitin<volok-aleksej@yandex.ru>

DAEMON=/usr/bin/twndeamon
NAME=twndeamon
PIDDIR=/var/run
PIDFILE=$PIDDIR/$NAME.pid
DESC="twainet deamon"

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

start_it_up()
{
  if [ -e $PIDFILE ]; then
    if $0 status > /dev/null ; then
      log_success_msg "$DESC already started; not starting."
      return
    else
      log_success_msg "Removing stale PID file $PIDFILE."
      rm -f $PIDFILE
    fi
  fi

  log_daemon_msg "Starting $DESC" "$NAME"
  start-stop-daemon --start --oknodo --pidfile $PIDFILE \
    --exec $DAEMON -- start
  log_end_msg $?
}

shut_it_down()
{
  log_daemon_msg "Stopping $DESC" "$NAME"
  start-stop-daemon --stop --retry 5 --oknodo --pidfile $PIDFILE
  log_end_msg $?
  rm -f $PIDFILE
}

case "$1" in
  start)
    start_it_up
  ;;
  stop)
    shut_it_down
  ;;
  restart)
    shut_it_down
    start_it_up
  ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 2
  ;;
esac